A3PREP(registerFiredMan);
A3PREP(exportAnalytics);
A3PREP(exportSession);
A3PREP(flushShotBuffer);
A3PREP(getSnapshotCount);
A3PREP(handleFiredMan);
A3PREP(handleKilled);
A3PREP(queryKills);
A3PREP(takeSnapshot);
