A3PREP(applyToTarget);
A3PREP(gui_addRule);
A3PREP(gui_deleteRule);
A3PREP(gui_editRule);
A3PREP(gui_listRules);
A3PREP(gui_loadPreset);
A3PREP(gui_savePreset);
A3PREP(openEditor);
A3PREP(validateRule);
