[default]
workshop = [
    "450814997", # CBA_A3
]
mission = "test.VR"
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-world=VR",
]
executable = "arma3_x64"
file_patching = true

[test]
extends = "default"
mission = "test.VR"
