[default]
workshop = [
    "450814997", # CBA_A3
]
mission = "Z:/ext/Development/a3db/.hemtt/missions/test.VR/mission.sqm"
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-world=VR",
]
executable = "arma3_x64"
file_patching = false

[test]
extends = "default"
mission = "Z:/ext/Development/a3db/.hemtt/missions/test.VR/mission.sqm"
