name = "a3db"
prefix = "a3db"
mainprefix = "z"
author = "ABE Team"

[files]
include = [
    "a3db.dll",
    "a3db.so",
    "a3db_*.dll",
    "a3db_*.so",
    "extension/target/release/a3db_*.dll",
    "extension/target/release/a3db_*.so",
    "mod.cpp",
    "docs/README.md",
    "meta.cpp",
]

[version]
major = 0
minor = 1
patch = 0
git_hash = 0

[hemtt.release]
folder = "a3db"
